name: Docker container API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t simple-app .
    - name: Run the Docker container
      run: |
        docker run -d --name simple-app-container -p 80:80 simple-app
        sleep 10 # Wait for the container to start
    - name: Test the API
      run: pytest tests/test_container.py --base-url http://localhost:8080
    - name: Stop the Docker container and delete the image
      run: |
        docker stop $(docker ps -q) # Stop all running containers
        docker container prune -f # Remove all stopped containers
        docker image prune -a -f # Remove all unused images
      if: always() # Ensure this step runs even if previous steps fail
